### With content
POST http://localhost:3000/api/notes/
Content-Type: application/json; charset=utf-8

{
    "content": "Me tengo que suscribir a @midudev en Youtube",
    "userId": "61e73f62de4152c348765048"
}

### With content and important
POST http://localhost:3000/api/notes/
Content-Type: application/json; charset=utf-8

{
    "content": "Tengo que estudiar las clases del Fullstack Bootcampo",
    "important": true,
    "userId": "61e73f62de4152c348765048"
}

### Empty
POST http://localhost:3000/api/notes/
Content-Type: application/json; charset=utf-8

{}

### No found
POST http://localhost:3000/api/notes/99