### All notes
http://localhost:3000/api/notes

### Individual note
http://localhost:3000/api/notes/61dddab130e170055fe1eaeb

### Individual note BadFormat ID
http://localhost:3000/api/notes/61dddab130e170055fe1eae